name: Lint & Test with coverage (vitest)

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  oxlint:
    name: Lint (fast pass)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@1.6.0 --deny-warnings
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    name: Test & Lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, lint and test with coverage
        run: |
          npm install
          npm run lint
          npm run ci
        env:
          CI: true
